### ISSUE TITLE
CompileError when passing model with integer division

### ISSUE THREAD

**Issue by amas0** [stan-dev/httpstan#566] opened 2021-05-15 17:43 UTC
Found an issue where httpstan will return a error code 400 "Bad Request" when passing model code that contains integer division, which generates the return message:

```
CompileError(DistutilsExecError(\"command '/usr/bin/gcc' failed with exit code 1\"))`, traceback: `['  File \"/home/amas/projects/httpstan/env/lib/python3.9/site-packages/httpstan/views.py\", line 114, in handle_create_model\\n    compiler_output = await httpstan.models.build_services_extension_module(program_code)\\n', '  File \"/home/amas/projects/httpstan/env/lib/python3.9/site-packages/httpstan/models.py\", line 168, in build_services_extension_module\\n    compiler_output = await asyncio.get_running_loop().run_in_executor(\\n', '  File \"/usr/lib/python3.9/concurrent/futures/thread.py\", line 52, in run\\n    result = self.fn(*self.args, **self.kwargs)\\n', '  File \"/home/amas/projects/httpstan/env/lib/python3.9/site-packages/httpstan/build_ext.py\", line 80, in run_build_ext\\n    build_extension.run()\\n', '  File \"/usr/lib/python3.9/distutils/command/build_ext.py\", line 340, in run\\n    self.build_extensions()\\n', '  File \"/usr/lib/python3.9/distutils/command/build_ext.py\", line 449, in build_extensions\\n    self._build_extensions_serial()\\n', '  File \"/usr/lib/python3.9/distutils/command/build_ext.py\", line 474, in _build_extensions_serial\\n    self.build_extension(ext)\\n', '  File \"/usr/lib/python3.9/distutils/command/build_ext.py\", line 529, in build_extension\\n    objects = self.compiler.compile(sources,\\n', '  File \"/usr/lib/python3.9/distutils/ccompiler.py\", line 574, in compile\\n    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)\\n', '  File \"/usr/lib/python3.9/distutils/unixccompiler.py\", line 120, in _compile\\n    raise CompileError(msg)\\n']
```

To recreate, run `httpstan` as normal and run the following curl command:

```bash
curl -H "Content-Type: application/json" \
    --data '{"program_code":"parameters {real y;} model {y ~ normal(0,1/5);}"}' \
    http://localhost:8080/v1/models
```

Note, this is the basic usage example in the README but with standard deviation 1/5 instead of 1. It should run for a bit as if it is building and then return the error. I conformed that the above model code will compile and sample properly if done with `cmdstan` directly. 

The model will compile without issue if the division is float division instead so the following works:

```bash
curl -H "Content-Type: application/json" \
    --data '{"program_code":"parameters {real y;} model {y ~ normal(0,1/5.0);}"}' \
    http://localhost:8080/v1/models
```

Somewhat of an odd issue, might have to do with how the model code is parsed when it receives it over HTTP? Not sure.

(As a side note, I found this issue when trying to run a model of mine -- turns out I had mis-specified the model and I didn't want integer division! Correctly specifying the model with float division fixed the issue... so in a way, this bug helped me find an error on my part :) still a bug though, it would seem )

**Comment by riddell-stan** [comment] 2021-05-16 17:48
Thanks for the report. This does indeed look like a bug.

The fix should be easy. Will need tests in httpstan and pystan.

**Comment by ahartikainen** [comment] 2021-05-16 17:51
I wonder if this error is actually raised by stanc.

**Comment by riddell-stan** [comment] 2021-05-17 22:22
Likely relevant https://github.com/stan-dev/stanc3/pull/869

**Comment by riddell-stan** [comment] 2021-05-17 22:37
Yes, I think this will be solved by the PR referenced above. The root cause of the problem is that the integer division warning is somehow ending up in the C++ code. Such code will, of course, not compile.

**Comment by rok-cesnovar** [comment] 2021-05-18 06:29
The warning is printed to stdout in stanc3, it should be printed to stderr. 

However I am not sure why that would cause it to end in the C++ code? Is pystan calling stanc3 so that it prints the C++ and consume the printed C++?

**Comment by riddell-stan** [comment] 2021-05-18 10:28
Yes, that's exactly what PyStan does.

**Comment by rok-cesnovar** [comment] 2021-07-11 10:24
The PR in stanc3 was merged so this issue was addressed upstream. I guess we can close?

**Comment by rok-cesnovar** [comment] 2021-07-11 14:18
Cool, then it has to wait for the next release.

**Comment by riddell-stan** [comment] 2021-07-11 15:38
That's correct. Let's keep this open until stanc makes a new release and httpstan uses it.

**Closed** 2021-10-05 17:50 UTC
Labels: bug
